version: '2'

services:
    caddy:
        image: caddy:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - D:/Workspace/TRAVLR/Repo/thebalibible:/app/public/tbb
            - D:/Workspace/TRAVLR/Repo/thebalibible-cms:/app/public/tbb-cms
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - php-web
        depends_on:
            - php-fpm

    php-fpm:
        container_name: php-fpm
        build: .
        volumes:
            - D:/Workspace/TRAVLR/Repo/thebalibible:/app/public/tbb
            - D:/Workspace/TRAVLR/Repo/thebalibible-cms:/app/public/tbb-cms
        networks:
            - php-web

volumes:
    caddy_data:
    caddy_config:

networks:
    php-web:
        driver: bridge